name: likora
description: Likora App

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/likora/
    - assets/lexion/

flutter_launcher_icons:
  ios: true
  image_path: "assets/likora/likora_ikon.png"